//! The CLI's DPoP proof key, and the proofs it signs.
//!
//! Every relay call on the connect path is DPoP-bound: the relay mints an
//! access token bound to this key's thumbprint, and each request carries a
//! fresh proof signed by it. The key is therefore as long-lived as the
//! credential and lives next to it, in the same owner-only config directory,
//! so removing that one directory removes everything this CLI holds.
//!
//! Both the file and the proof are cross-implementation formats, so both are
//! ported rather than invented:
//!
//! * `~/.config/svartal/dpop.jwk.json` is the same file the npm CLI writes
//!   (`packages/shared/src/dpopKeyFile.ts`): one private JWK,
//!   `{kty, crv, x, y, d}`, mode `0600`.
//! * the proof is `createDpopProof` in `packages/shared/src/dpopProof.ts`:
//!   `typ: dpop+jwt`, `alg: ES256`, the public JWK in the header, claims
//!   `htm`/`htu`/`jti`/`iat` and `ath` when an access token is presented,
//!   signed over `header.payload` with a raw `r||s` signature.
//!
//! `tests/dpop_compat.rs` pins both against fixtures generated by that
//! TypeScript code (`tests/fixtures/generate-dpop.mjs`).

use std::path::Path;

use p256::ecdsa::signature::Signer as _;
use p256::ecdsa::{Signature, SigningKey};
use p256::{EncodedPoint, SecretKey};
use serde::{Deserialize, Serialize};
use serde_json::json;
use url::Url;

use crate::fsutil;
use crate::jwt::{b64url_decode, b64url_encode};
use crate::oidc::sha256;

pub const DPOP_TYP: &str = "dpop+jwt";
pub const DPOP_ALG: &str = "ES256";

/// Named for what it is, so a person who finds it knows what deleting it costs
/// (a new thumbprint, and therefore a new relay token — nothing else).
pub const DPOP_KEY_FILE_NAME: &str = "dpop.jwk.json";

const MAX_KEY_FILE_BYTES: u64 = 4_096;

#[derive(Debug)]
pub struct DpopError(pub String);

impl std::fmt::Display for DpopError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for DpopError {}

/// The public half, in the field order the reference implementation writes it:
/// `publicJwkOf` builds `{kty, crv, x, y}`, and that object is serialized into
/// the proof header, so the order is part of the signed bytes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PublicJwk {
    pub kty: String,
    pub crv: String,
    pub x: String,
    pub y: String,
}

/// The private half, the only shape that can be written down.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrivateJwk {
    pub kty: String,
    pub crv: String,
    pub x: String,
    pub y: String,
    pub d: String,
}

pub struct DpopKey {
    signing_key: SigningKey,
    public_jwk: PublicJwk,
    thumbprint: String,
}

impl DpopKey {
    pub fn public_jwk(&self) -> &PublicJwk {
        &self.public_jwk
    }

    /// RFC 7638 thumbprint, base64url. This is what the relay binds a token to.
    pub fn thumbprint(&self) -> &str {
        &self.thumbprint
    }

    pub fn from_private_jwk(jwk: &PrivateJwk) -> Result<Self, DpopError> {
        if jwk.kty != "EC" || jwk.crv != "P-256" {
            return Err(DpopError("the DPoP key is not an EC P-256 key".to_string()));
        }
        let scalar = decode_coordinate(&jwk.d, "d")?;
        let secret = SecretKey::from_slice(&scalar)
            .map_err(|_| DpopError("the DPoP private key is not a P-256 scalar".to_string()))?;
        let key = Self::from_secret(secret);
        // The stored public half has to be the one this scalar produces.
        // Trusting a mismatched `x`/`y` would sign proofs against a thumbprint
        // no token was ever bound to, and the failure would surface much later
        // as an unexplained refusal.
        if key.public_jwk.x != jwk.x || key.public_jwk.y != jwk.y {
            return Err(DpopError(
                "the DPoP key file's public and private halves disagree".to_string(),
            ));
        }
        Ok(key)
    }

    fn from_secret(secret: SecretKey) -> Self {
        let point = EncodedPoint::from(secret.public_key());
        let x = b64url_encode(point.x().map(|value| &value[..]).unwrap_or_default());
        let y = b64url_encode(point.y().map(|value| &value[..]).unwrap_or_default());
        let public_jwk =
            PublicJwk { kty: "EC".to_string(), crv: "P-256".to_string(), x, y };
        let thumbprint = jwk_thumbprint(&public_jwk);
        Self { signing_key: SigningKey::from(&secret), public_jwk, thumbprint }
    }

    fn to_private_jwk(&self) -> PrivateJwk {
        PrivateJwk {
            kty: self.public_jwk.kty.clone(),
            crv: self.public_jwk.crv.clone(),
            x: self.public_jwk.x.clone(),
            y: self.public_jwk.y.clone(),
            d: b64url_encode(&self.signing_key.to_bytes()),
        }
    }

    /// Sign one proof for one request.
    ///
    /// The proof is bound to the method and the URL, so there is one proof per
    /// call and none of them is reusable. That is the point of DPoP and not an
    /// inefficiency to optimize away.
    pub fn create_proof(&self, request: &ProofRequest<'_>) -> Result<String, DpopError> {
        let htu = normalize_htu(request.url)
            .ok_or_else(|| DpopError("Could not normalize DPoP proof URL.".to_string()))?;
        let header = json!({
            "typ": DPOP_TYP,
            "alg": DPOP_ALG,
            "jwk": self.public_jwk,
        });
        let mut payload = json!({
            "htm": request.method.to_uppercase(),
            "htu": htu,
            "jti": request.jti,
            "iat": request.issued_at_seconds,
        });
        if let Some(access_token) = request.access_token {
            payload
                .as_object_mut()
                .expect("payload is an object")
                .insert("ath".to_string(), json!(access_token_hash(access_token)));
        }
        let encode = |value: &serde_json::Value| -> Result<String, DpopError> {
            serde_json::to_vec(value)
                .map(|bytes| b64url_encode(&bytes))
                .map_err(|error| DpopError(format!("could not encode the DPoP proof: {error}")))
        };
        let signing_input = format!("{}.{}", encode(&header)?, encode(&payload)?);
        let signature: Signature = self.signing_key.sign(signing_input.as_bytes());
        Ok(format!("{signing_input}.{}", b64url_encode(&signature.to_bytes())))
    }
}

#[derive(Debug, Clone)]
pub struct ProofRequest<'a> {
    pub method: &'a str,
    pub url: &'a str,
    /// Present on a resource request: binds the proof to the token presented
    /// with it.
    pub access_token: Option<&'a str>,
    pub jti: &'a str,
    pub issued_at_seconds: i64,
}

impl<'a> ProofRequest<'a> {
    /// A proof for right now, with a fresh identifier. The explicit fields stay
    /// public so a fixture test can pin them.
    pub fn now(method: &'a str, url: &'a str, access_token: Option<&'a str>, jti: &'a str) -> Self {
        Self {
            method,
            url,
            access_token,
            jti,
            issued_at_seconds: crate::now_epoch_ms() / 1_000,
        }
    }
}

pub fn dpop_key_file_path(state_directory: &Path) -> std::path::PathBuf {
    state_directory.join(DPOP_KEY_FILE_NAME)
}

/// The stored proof key, generated and persisted on first use.
///
/// A key file that exists but cannot be read is an error, never a reason to
/// mint a new one: a new thumbprint silently invalidates every token bound to
/// the old one.
pub fn load_or_create_key(state_directory: &Path) -> Result<DpopKey, DpopError> {
    let path = dpop_key_file_path(state_directory);
    let existing = fsutil::read_private_file(&path, MAX_KEY_FILE_BYTES)
        .map_err(|error| DpopError(format!("Could not read the Svartal proof key: {error}")))?;
    if let Some(bytes) = existing {
        let jwk: PrivateJwk = serde_json::from_slice(&bytes).map_err(|_| {
            DpopError(format!(
                "{} does not hold a usable DPoP key. Delete it to start a new one.",
                path.display()
            ))
        })?;
        return DpopKey::from_private_jwk(&jwk);
    }
    let key = generate_key()?;
    let body = serde_json::to_vec(&key.to_private_jwk())
        .map_err(|error| DpopError(format!("could not serialize the DPoP key: {error}")))?;
    fsutil::write_private_file(&path, &body)
        .map_err(|error| DpopError(format!("Could not write the Svartal proof key: {error}")))?;
    Ok(key)
}

pub fn generate_key() -> Result<DpopKey, DpopError> {
    // A random 32-byte string is a valid P-256 scalar unless it happens to be
    // zero or above the group order; both are vanishingly unlikely, and the
    // honest answer to "unlikely" is to draw again rather than to reduce.
    for _ in 0..8 {
        let mut bytes = [0u8; 32];
        getrandom::getrandom(&mut bytes)
            .map_err(|_| DpopError("the system random source is unavailable".to_string()))?;
        if let Ok(secret) = SecretKey::from_slice(&bytes) {
            return Ok(DpopKey::from_secret(secret));
        }
    }
    Err(DpopError("could not generate a DPoP key".to_string()))
}

/// RFC 7638: SHA-256 over the required members in lexicographic order,
/// base64url. For an EC key that is `crv`, `kty`, `x`, `y` — which is exactly
/// what the reference implementation's `stableStringify` produces.
pub fn jwk_thumbprint(jwk: &PublicJwk) -> String {
    let input = format!(
        r#"{{"crv":{},"kty":{},"x":{},"y":{}}}"#,
        json_string(&jwk.crv),
        json_string(&jwk.kty),
        json_string(&jwk.x),
        json_string(&jwk.y)
    );
    b64url_encode(&sha256(input.as_bytes()))
}

/// The `ath` claim: base64url of the SHA-256 of the access token.
pub fn access_token_hash(access_token: &str) -> String {
    b64url_encode(&sha256(access_token.as_bytes()))
}

/// `normalizeDpopHtu`: the request URL with query and fragment removed,
/// serialized the way a browser's `URL` would.
pub fn normalize_htu(url: &str) -> Option<String> {
    let mut parsed = Url::parse(url).ok()?;
    parsed.set_fragment(None);
    parsed.set_query(None);
    Some(parsed.to_string())
}

/// A version 4 UUID, the identifier shape `createDpopProof` uses for `jti`.
pub fn random_uuid_v4() -> Result<String, DpopError> {
    let mut bytes = [0u8; 16];
    getrandom::getrandom(&mut bytes)
        .map_err(|_| DpopError("the system random source is unavailable".to_string()))?;
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    Some(format!(
        "{}-{}-{}-{}-{}",
        &hex[0..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..32]
    ))
    .ok_or_else(|| DpopError("could not format a proof identifier".to_string()))
}

fn json_string(value: &str) -> String {
    serde_json::Value::String(value.to_string()).to_string()
}

fn decode_coordinate(value: &str, label: &str) -> Result<[u8; 32], DpopError> {
    let bytes = b64url_decode(value)
        .ok_or_else(|| DpopError(format!("the DPoP key field {label} is not base64url")))?;
    if bytes.len() != 32 {
        return Err(DpopError(format!("the DPoP key field {label} is not 32 bytes")));
    }
    let mut fixed = [0u8; 32];
    fixed.copy_from_slice(&bytes);
    Ok(fixed)
}
